import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const font = Montserrat({ subsets: ['latin'] })

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${font.className}`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}
